### ISSUE TITLE
remote distributionMode

### ISSUE THREAD

**Issue by joreilly** [ge-org/multiplatform-swiftpackage#24]
This is probably more a question rather than issue but wasn't clear from docs how remote `distributionMode` should work.  If I have package hosted for example on Github should this allow uploading generated artifacts to there?  btw wrote short post on experience using plugin so far (in case anything you think isn't quite right there or should be clarified ) https://johnoreilly.dev/posts/kotlinmultiplatform-swift-package/

**Comment by ge-org** [comment]
Hi, thanks for your feedback.
The remote mode is not meant to upload artifacts to a remote source. It rather serves as a workaround since Xcode cannot currently download artifacts from a Git repository other than Github (afaik). However, it can download from a static URL. So you should upload the ZIP file (with some Gradle task or other means) to the URL declared in `remote("https:// ....")`. This way Xcode should be able to download the framework correctly. 

I hope this helps with your question. If you have any other use case or a better suggestion please let me know.

The blog posts is well written, great job, thanks!
